### ISSUE TITLE
💡If JavaFX runtime components are missing, you missed lines in gradle.build file

### ISSUE THREAD

**Issue by l-shihao** [nus-tic4002-AY2122s2/forum#1]
If you follow the [ JavaFX tutorial @SE-EDU/guides](https://se-education.org/guides/tutorials/javaFxPart1.html) > **If you are using Gradle** section, you may get below error, by copying just the code snippet: 

> Task :run FAILED
Error: JavaFX runtime components are missing, and are required to run this application

Besides the code provided that adds inside `dependencies {}`, you should also add below 👇
```
plugins {
  id 'application'
  id 'org.openjfx.javafxplugin' version '0.0.11'
}

javafx {
    modules = [ 'javafx.controls', 'javafx.fxml']
}
```
in order to download the necessary components, according to [Getting Started with JavaFX](https://openjfx.io/openjfx-docs/#gradle).

**Comment by damithc** [comment]
Thanks for sharing this @l-shihao 💯

**Comment by gweeyc** [comment]
For the gradle codes shown below, adding the suggested above plugins do not work:
![image](https://user-images.githubusercontent.com/43993134/152366824-8a230491-019d-434a-abc4-e4e64f270d0e.png)

For the latter case, I find one need to create a module-info.java file to make it compile and run successfully:
![image](https://user-images.githubusercontent.com/43993134/152367241-7e083b1e-52b0-4e0f-b37f-adaf36f9ef9a.png)

Then you can include the usual main method in Duke.java file itself like this:
![image](https://user-images.githubusercontent.com/43993134/152368599-9b62e56f-8b9d-4a59-b72f-758dc2d63a29.png)
When you click the green arrow in Intellij IDE to run Duke.main() the program will compile and run successfully.


**NB: -** 
- Module-info.java cannot work with the default package mode. One needs to specifically create a new package (name it your way) to house your Duke.java as shown in the snapshot above.
- Place the module-info.java file in the java source root directory only.

**Comment by gweeyc** [comment]
I find it is best not use module-info.java if not familiar with Java modules configuration. The above config is for simple testing phase. Best follow the standard config outlines as shown per textbook instructions.
