### ISSUE TITLE
Adding tP Team Org query

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#11]
### **For our tP Team Organization setup: -**
![image](https://user-images.githubusercontent.com/43993134/152972120-875c48c5-2609-4490-ad1a-5413241e9463.png)
**Are we still using F18? Eg. if we are team 5, do we create our org as AY2122S2-TIC4002-F18-5?**

**Comment by damithc** [comment]
@gweeyc yes, use F18. That's the tutorial slot identifier. Although TIC4002 has only one tutorial slot, some of the module tools expects the team ID to follow that format.

**Comment by gweeyc** [comment]
Got it. Thanks!
