### ISSUE TITLE
Increment CI setup upload has errors?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#13]
Hi Profs,
My CI setup increment output this Error Msg:
![image](https://user-images.githubusercontent.com/43993134/153123750-12bf5ef0-6192-4c2b-96dd-f684e26a6f00.png)

How do I resolve this error?

Thank you!

**Comment by damithc** [comment]
@gweeyc see if this helps https://github.com/nus-cs2103-AY2122S2/forum/issues/115

**Comment by gweeyc** [comment]
HI Prof Damith,
I tried the above solutions but I receive this error msg instead:
![image](https://user-images.githubusercontent.com/43993134/153127312-e238a0f3-4744-48a7-8931-a1f2d3074b6a.png)

**Comment by damithc** [comment]
@gweeyc You can try a dirty workaround of trying to update those files using GitHub Web interface, which allows adding/editing a one file at a time. See if that works.

**Comment by gweeyc** [comment]
Hi Profs,
Think previously my delegation of github authentication to third party Sourcetree caused the issue.
I managed to solve the problem after trial and error and some good luck googling!

### The basic steps, following after the previous ref thread you mentioned:

1. Clear out the github and sourcetree credentials
2. Create a new PAT from Github Developer settings, as per standard procedure (ensure workflow option is checked)
3. Open Sourcetree and go to Settings -> change the origin remote url entry to https://<username>:<new PAT token>@<repo_url_strings>.git
4. Push the commit upstream, it goes through successfully!
5. To ensure PAT does not remain visible, go to Sourcetree -> Tools -> Options -> Git -> Git Version, click the System button. Click OK (ensure Allow Sourcetree to manage my credentials via the Git Credential Manager is checked).
6. Then just go back to the remote origin url Settings, write over it with the repo git url (copied as usual from your Github repo straight). 
7. Now you can push as per normal without PAT being exposed visibly!

I tested the CLI setup workflow next and it continues to work fine!
![image](https://user-images.githubusercontent.com/43993134/153136477-146ef6e0-d76d-4ce9-a441-b094926a9dff.png)

**Comment by damithc** [comment]
Nice work @gweeyc 💯 
Thanks for sharing this. Will be useful to other students as well.

**Comment by gweeyc** [comment]
Thank you. Resolved.
