### ISSUE TITLE
Why there is double Java CI done ?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#14]
HI Profs,
I checked in my github repo after finishing the BCD-Extension:
![image](https://user-images.githubusercontent.com/43993134/153248065-5a6de39b-3957-442c-9c87-cf32590c6cc6.png)

Is this normal? It seems one is done for BCD-Extension, one for master ?

**Comment by damithc** [comment]
@gweeyc you can ignore that. Probably caused by pushing a tag or a branch.

**Comment by gweeyc** [comment]
Noted and thanks!
