### ISSUE TITLE
Upon opening the cloned repo in Intellij, an error msg on badge.avg?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#16]
Upon opening the cloned repo in Intellij first time I saw the IDE error is as shown:-
![error1](https://user-images.githubusercontent.com/43993134/153422143-f7c651fc-ad58-4d20-abdd-2658d1fb9ef5.jpg)

How can this issue be resolved? Thank you!

**Comment by vimuthm** [comment]
Hi Mr. Alvin @gweeyc ,

Are you still facing this issue? If so, can you provide a text output of the entire error log, it might help myself and others to better understand the origin of the error.

Thank you!

**Comment by gweeyc** [comment]
No, somehow when I open it again it has disappeared. Thanks! Resolved.
