### ISSUE TITLE
Upon first testing main method of cloned repo: error logs shown?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#17]
I try to run the main method of the local cloned repo of address book, and saw this error logs:-
![error_mainRun](https://user-images.githubusercontent.com/43993134/153422765-20d24c5a-d0ae-4df9-b785-6450a3ee6ad5.jpg)

How can this the issue be resolved? Thanks!

**Comment by limzk126** [comment]
Hi @gweeyc, I am an alumni of the undergraduate version of your course (Dropping by to see if i can help you guys with any technical problems!)

The logs are displaying *not found* as the files `config.json`, `preferences.json` and `addressbook.json` are not created yet when you first cloned the repo. However, after you first run the application and *then* close it, the `config.json` and `preferences.json` files will be created. The `addressbook,json` file will only be created if you have added/modified a contact to the addressbook.

Now you might be wondering, if all these files does not exist at the start, how did the addressbook app run normally?
If you trace the addressbook codebase thoroughly, you will realize that addressbook uses its own hardcoded default values for `config.json` as well as `preferences.json` if they are not created yet. As for `addressbook.json`, a backup/sample json file that contains sample contacts will be loaded as the storage. That is why you will see some contacts in the addressbook when you first run it eventhough you have not created any beforehand.

The purpose of the 3 files:
* `config.json`: To specify the levels of your logs and to provide the path to the `preferences.json` file.
* `preferences.json`: To specify the dimensions of your GUI when you first load the application and provide the path to the `addressbook.json` file.
* `addressbook.json`: Acts as a database/storage to store data such as your contacts and their information.

I think this is an intended behavior of the application and should not be of any problem. However, if you want extra reassurance you could email your module coordinator about this.

**Comment by gweeyc** [comment]
Hi @limzk126, will take note and thank you for the detailed explanations!
