### ISSUE TITLE
Gradle.built file deprecated item archivename?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#18]
In the gradle.build file, Intellij shows this msg for the archivename:-
![image](https://user-images.githubusercontent.com/43993134/153432125-742d29bd-6bef-4dc7-ba9d-4eb9a726113d.png)

Can we safely ignore this strikethrough item in Intellij?

**Comment by vimuthm** [comment]
Hi Mr. Alvin @gweeyc ,

Personally, I don't think it is a major issue to leave it as is. Deprecated usually means it's not supported anymore but this should function as needed for the time being.
 
I'm not sure of the gradle version in use/recommended but try changing `archiveName` -> `archiveBaseName`, might work given the version.

**Comment by gweeyc** [comment]
Noted and thank you. Yes it works.
