### ISSUE TITLE
Can we upgrade gradle version to latest version for our project?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#19]
Can we upgrade gradle v7.4 latest version? I find that it helps to smooth out a lot of compatibility issues often:
![image](https://user-images.githubusercontent.com/43993134/153432599-1ee92216-824f-4335-9ed4-850d0a21d4b6.png)

**Comment by damithc** [comment]
@gweeyc I think best to stick with the current version of Gradle as the whole class will be using that. Otherwise there could be compatibility issues between team members.
It is not uncommon for brownfield systems to use older versions of software, due to legacy reasons.

**Comment by gweeyc** [comment]
Ok noted.
