### ISSUE TITLE
Current Intellij IDEA Checkstyle Plugin version buttons now all colorless?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#20]
I was surprised when I run the Intellij IDEA Checkstyle Plugin, the side bar buttons are all colorless? Attached is a snapshot of the issue:-
![image](https://user-images.githubusercontent.com/43993134/153436912-98393a17-8dae-45e3-8fee-68ac63d65555.png)

**Comment by AllardQuek** [comment]
That seems odd. Have you tried restarting your IntelliJ?

**Comment by gweeyc** [comment]
Hi @AllardQuek ,
Now when I open Intellij again I saw the button colors all come back! Thanks! Resovled.
