### ISSUE TITLE
GitHub Java CI Build Fail, but local gradle run successful 

### ISSUE THREAD

**Issue by l-shihao** [nus-tic4002-AY2122s2/forum#21]
Java CI on GitHub Actions:
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/10278682/153437711-d2d83ce4-938e-407b-8ab9-003ceb878e19.png">
While locally, I could pass my `gradle run` or `gradle checkstyleMain checkstyleTest`
<img width="1260" alt="Screenshot 2022-02-10 at PM11 20 51" src="https://user-images.githubusercontent.com/10278682/153438702-4cf93b91-dd0f-4ca6-9bed-c3024558befe.png">
What could go wrong here? 
----
how come text so large. Seems GitHub also got bugs, previously my local file name and file name on GitHub is different despite `git push`.

**Comment by damithc** [comment]
You don't seem to have this file in your fork 
![image](https://user-images.githubusercontent.com/1673303/153440716-73a9fac8-4bde-4ee9-935f-f088823e2725.png)

**Comment by l-shihao** [comment]
I see, I put `config/` in my `.gitingnore` file, that's why the directory on my GitHub does not have the `checkstyle.xml`
