### ISSUE TITLE
Does Jar file include CSS? 

### ISSUE THREAD

**Issue by l-shihao** [nus-tic4002-AY2122s2/forum#22]
My guess is no, as jar file clearly lost my `/data/duke.txt` file
Because if I run my program in Intellij IDEA (I used CSS as below)

<img width="428" alt="image" src="https://user-images.githubusercontent.com/10278682/153440497-d1ea2444-0351-459b-81bc-f6aa1b72abe1.png">

I could get monospace font:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/10278682/153440915-275865d4-9aeb-4c0d-be23-1e88e288d120.png">

If I double click to launch the `shadowJar` generated `jar` file, I lost the font: 

<img width="572" alt="image" src="https://user-images.githubusercontent.com/10278682/153441249-63f59c35-04cd-473f-94a0-63d7aee7d498.png">

So, 
1. If not include, how could we make use of CSS when release a `jar` file?
2. seems also there is some UTF-8 related char encoding issue, the check mark ✓ sometimes can work sometimes cannot

**Comment by damithc** [comment]
Your data file will not be in the JAR file. The code needs to create that folder and file when the application is run for the first time. If it is inside the JAR file, the file cannot be updated when more tasks are added.
CSS files are meant to be included in the JAR file, just like the image files.
Best not to use  ✓ . Use a regular char instead. e.g., `[  ]` and `[x]` for not done and done.

**Comment by damithc** [comment]
@l-shihao you can compare yours to the iPs posted in this thread (from another module) to see what's different in yours https://github.com/nus-cs2103-AY2122S2/forum/issues/81

**Comment by l-shihao** [comment]
In scene builder, the CSS has to be included in the top level component, not the leaf components to take effect

**Comment by damithc** [comment]
> In scene builder, the CSS has to be included in the top level component, not the leaf components to take effect

Thanks for sharing this @l-shihao
