### ISSUE TITLE
Is this a Dashboard bug?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#23]
Hi Profs,
This morning I saw the Dashboard report as shown below on my account:-
![image](https://user-images.githubusercontent.com/43993134/153528356-e02b98d7-75e0-41c8-9780-8521cb98a5fc.png)

Can this a bug of some sort ? Thank you!

**Comment by damithc** [comment]
@gweeyc Click on the (i) icon to find the commit period considered for week 4. Then, check if your fork to see if it has commits in that period.

**Comment by gweeyc** [comment]
Hi Prof Damith,
I get it, as for Week 4, all my commits are done after Feb 03, just that I am a bit unclear how the Dashboard works. According to the legend:
![image](https://user-images.githubusercontent.com/43993134/153532714-80d75bfb-c69d-4e2f-9ca9-0c25c0f3dc3c.png)

the red color means not done yet. But I have already done the Week 4 tags, so I was thinking it will auto update like last time (but I forgot then I did not fall behind schedule before!). Thank you.

**Comment by damithc** [comment]
> the red color means not done yet. But I have already done the Week 4 tags, so I was thinking it will auto update like last time (but I forgot then I did not fall behind schedule before!). Thank you.

@gweeyc `!4` tracks commits done during the week, not increments allocated to that week i.e., it tracks consistency of work over the project period. Weekly increments are tracked separately and individually. 

![image](https://user-images.githubusercontent.com/1673303/153533613-f00b1a6a-e05a-4e07-b430-c6fcb3b10d5a.png)

**Comment by damithc** [comment]
BTW, not to worry about having a week without commits. You can get full marks if you have committed code in most weeks, not necessarily _all_ weeks.

**Comment by gweeyc** [comment]
Noted and thank you. Resolved.
