### ISSUE TITLE
The dateline for our v1.2 UG Draft?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#24]
HI Profs,
I'm not sure when to submit the v1.2 UG Draft? Is it by the dateline shown in Luminus actually?
![image](https://user-images.githubusercontent.com/43993134/153544706-46f5aa6c-8f85-42bf-8fd4-00769072328f.png)

**Comment by damithc** [comment]
@gweeyc It's a deliverable for week 5, which ends today.
LumiNUS is showing the folder closing date as the deadline, possibly a LumiNUS bug.

**Comment by gweeyc** [comment]
Noted and thanks!
