### ISSUE TITLE
A an exception error message remain upon opening up the addressbook app in Intellij?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#25]
Hi Profs,
I saw the last exception error still shows as the snapshot below indicates:-
![image](https://user-images.githubusercontent.com/43993134/153580729-809ab676-69d9-43bb-a17a-7ee16287d597.png)

What does this error refer to?

**Comment by damithc** [comment]
@gweeyc Is it still happening? When does it happen exactly?

**Comment by gweeyc** [comment]
HI Prof Damith,
I believe this conflict comes from installing the latest CheckStyle plugin for Intellij to run it in Intellij. Think our original project configuration already has the earlier version of logger enabled, so the conflict.

I have uninstalled the plugin and just run the checkstyle from Gradle. There is no more exception error.

Thanks!
