### ISSUE TITLE
💎Can Ref this URL for the color settings for various JavaFx elements

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#26]
https://openjfx.io/javadoc/11/javafx.graphics/javafx/scene/doc-files/cssref.html

![image](https://user-images.githubusercontent.com/43993134/153708727-34e25c0e-8a9e-4f08-8387-8e10d1652e8e.png)

**Comment by damithc** [comment]
Thanks for sharing this @gweeyc

**Comment by gweeyc** [comment]
Thanks.
