### ISSUE TITLE
Caused by: java.lang.NoSuchMethodException: duke.Duke.<init>()

### ISSUE THREAD

**Issue by zyjarvis** [nus-tic4002-AY2122s2/forum#27]
I have experienced the error of java.lang.NoSuchMethodException: duke.Duke.<init>() after implementing GUI.

Anyone knows what the error refers to and how to solve it?

<img width="893" alt="image" src="https://user-images.githubusercontent.com/54254521/153738209-53e4aeb1-8e15-47fa-913b-c705df4e6256.png">

**Comment by damithc** [comment]
@zyjarvis pls push your exact code to a branch and post the link here so that someone can help troubleshoot for you.
Keep in mind that you need to update build.gradle to point to the main method that should be run to start the GUI.

**Comment by zyjarvis** [comment]
Please refer to this link: https://github.com/zyjarvis/ip/tree/add-a-GUI

**Comment by limzk126** [comment]
Hi @zyjarvis ,

You need to change the access level of the `Duke`'s constructor to *public*. Because it is set to *private*, `Launcher` was unable to instantiate a `Duke` object to invoke its `start` method.

**Comment by zyjarvis** [comment]
Oh, It works finally.

Thanks a lot. @limzk126
