### ISSUE TITLE
How to edit the Github pages title?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#28]
Hi how to edit the LisGenie ChatBot Task Manager 2.0 shown below in github-pages? 
![image](https://user-images.githubusercontent.com/43993134/153855655-adcd7c67-2110-45ed-a652-f54846c0c7aa.png)

**Comment by damithc** [comment]
@gweeyc It must be picking it up from somewhere in your repo. Just need to figure out from where.

**Comment by gweeyc** [comment]
Noted and Thanks!
