### ISSUE TITLE
The Tutorial Tracing Code Debug No frames shown issue in Debugger

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#29]
Hi Profs,
I try the week 5 Tutorial Tracing Code but I got this issue:
![image](https://user-images.githubusercontent.com/43993134/154422154-e25ed0fb-29a7-4746-8fdb-a6f5fac63b16.png)

It shows no frames at all, how can I then debug on? Thank you.

**Comment by damithc** [comment]
@gweeyc where did you put the break point? Is the AB3 GUI already visible when you took the screenshot?

**Comment by gweeyc** [comment]
Yes, I input the edit command and it shows the result upfront! Though I had put the break on the MainWindow#executeCommand()?

![image](https://user-images.githubusercontent.com/43993134/154434798-ba883acc-1364-4ded-a23d-50b9ae63ea6b.png)

It seems it just pass through?

**Comment by gweeyc** [comment]
Nonessential, bypassed for now. May need to do re setup.
