### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by YangShuogeng** [nus-tic4002-AY2122s2/forum#31]
Hi Prof.,

I use Windows OS and generated a JAR file by using the `shadowJar` function in Gradle. I met a problem when I tried to run the JAR file in CMD as shown below: 

![image](https://user-images.githubusercontent.com/54273624/154708839-c2f6326b-c17f-4bbf-86d5-d956249a4299.png)

Sorry that my OS is in Chinese so that the cmd error got chinese:

The error: Cannot find or load the main class seedu.duke.Duke
Reason: java.lang.ClassNotFoundException: seedu.duke.Duke

Is there some Idea setting wrongly? How can I solve the problem?

Thanks a lot prof.

**Comment by damithc** [comment]
@YangShuogeng do you have a class `seedu.duke.Duke`? If not, you'll probably need to locate where it is mentioned and update it to match your code. Perhaps `build.gradle`?

**Comment by YangShuogeng** [comment]
Hi Prof.,

Noted with thanks.

I will try to figure out.

________________________________

**Comment by YangShuogeng** [comment]
> @YangShuogeng do you have a class `seedu.duke.Duke`? If not, you'll probably need to locate where it is mentioned and update it to match your code. Perhaps `build.gradle`?

I can pass `build.gradle` in Idea. But still got this issue.

**Comment by damithc** [comment]
> I can pass `build.gradle` in Idea.

Not sure what that means 🤔 
You need to check the content of `build.gradle` to check if it refers to the non-existent file `seedu.duke.Duke`

**Comment by YangShuogeng** [comment]
> > I can pass `build.gradle` in Idea.
> 
> Not sure what that means 🤔 You need to check the content of `build.gradle` to check if it refers to the non-existent file `seedu.duke.Duke`

Noted. I'll check it.

**Comment by YangShuogeng** [comment]
> > I can pass `build.gradle` in Idea.
> 
> Not sure what that means 🤔 You need to check the content of `build.gradle` to check if it refers to the non-existent file `seedu.duke.Duke`

Thanks a lot prof.. The problem settle. In `build.gradle` file, I found that the `mainClassName` is assigned `seedu.duke.Duke`. I changed it to `Launcher`, then the problem solved.

**Comment by damithc** [comment]
Good to hear that @YangShuogeng 
You can go ahead and close this issue.

**Comment by YangShuogeng** [comment]
Thanks prof.. Problem solved.
