### ISSUE TITLE
TO update the README file v1.1

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#32]
For the tP2, I notice that it uses the index.md instead of README file. 
Can we just update using the index.md file straight? As I find using a README.md can create some issues integrating with tP2 overall structure?

**Comment by damithc** [comment]
@gweeyc The two files are for two different purposes. README.md (e.g., https://github.com/nus-tic4002-AY2122s2/tp2) is for those who visit the GitHub **project**, and index.md is for those who visit the **product** website (e.g., https://nus-tic4002-ay2122s2.github.io/tp2/) .

**Comment by gweeyc** [comment]
Thank you.
