### ISSUE TITLE
CI failed in my own fork repository but not the team org repository

### ISSUE THREAD

**Issue by l-shihao** [nus-tic4002-AY2122s2/forum#35]
Seems related to this `codecov` thing, I didn't find the `coverage/coverage.xml` under `build/reports/jacoco` also. 
I guess something in the `build.gradle` needs to be fixed?

<img width="1636" alt="image" src="https://user-images.githubusercontent.com/10278682/155838689-aed6f262-1f59-4c60-989c-8ba83b6c0ac2.png">

**Comment by damithc** [comment]
@l-shihao No need to run CI on your own fork. But if you do want to run CI on your fork, remember to enable CodeCov for your fork, the same way you (or a team member) did it for the team repo.
