### ISSUE TITLE
Individual Dashboard update not showing correctly?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#36]
I have done all the tags except v1.2 but the Dashboard shows this:
![image](https://user-images.githubusercontent.com/43993134/155868377-2cf81fdf-0e49-4798-a24e-982a3b06c9c9.png)

My photo is showing in the AboutUs.md:-
![image](https://user-images.githubusercontent.com/43993134/155868419-0ea86f96-fd5b-475a-b978-b7ab8d48ced0.png)

Submitted at least 1 v1.1 PR successfully merged:-
![image](https://user-images.githubusercontent.com/43993134/155868455-a358d0a6-3685-4066-a186-2b93a8bfca24.png)

Thank you!

**Comment by damithc** [comment]
@gweeyc click on the (i) icon to find more details about the requirements.
The PRs need to follow the forking workflow (e.g., each should be from a separate branch).
Regarding the photo, you have not met the requirement yet if the photo doesn't show up in https://nus-tic4002-ay2122s2.github.io/website/admin/teamList.html

**Comment by gweeyc** [comment]
HI Prof Damith,
I find the JavaCI Passing badges all point to our Team 5 github repo workflow in the teamList.html ! Something is not right, can you kindly check for us? Thank you! 

Regarding the photo not showing, I do not know why as it is supposed to show as I have uploaded the photo to AboutUs.md page already with the right username format? Maybe I redo with a separate branch and hope that will solve that.

**Comment by damithc** [comment]
> I find the JavaCI Passing badges all point to our Team 5 github repo workflow in the teamList.html ! Something is not right, can you kindly check for us? Thank you!

This is the code of your index.md https://raw.githubusercontent.com/AY2122S2-TIC4002-F18-5/tp2/master/docs/index.md

You need to update the following line, so that it points to your team fork:
```
[![CI Status](https://github.com/se-edu/addressbook-level3/workflows/Java%20CI/badge.svg)](https://github.com/se-edu/addressbook-level3/actions)
```


> Regarding the photo not showing, I do not know why as it is supposed to show as I have uploaded the photo to AboutUs.md page already with the right username format? Maybe I redo with a separate branch and hope that will solve that.

I don't think you have followed this filename requirement exactly. Probably misunderstood the requirement. See the example provided in the screenshot below. 
![image](https://user-images.githubusercontent.com/1673303/155869466-48a8266a-53be-4469-b88d-e93b54ff3984.png)

**Comment by gweeyc** [comment]
Hi Prof, understand now, thank you for the correct interpretations. Will update the relevant details now.
