### ISSUE TITLE
Where to get the Java CI passing badge?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#37]
I saw this in index.md:-
![image](https://user-images.githubusercontent.com/43993134/155869058-2146001f-27b0-4c33-8e39-51f5d453b848.png)

Where can I get or generate the Java CI passing badge as our application has not been modified yet till next week? Can I just paste the image file or I need to generate with URL?

**Comment by damithc** [comment]
@gweeyc You should be able to get the link for the CI badge somewhere from your team repo settings as the GitHub actions is already running for your team repo.
Alternatively, you can examine the current link to figure out how to update it to match your team repo (just replace org/repo part of the badge link to match your team repo)

**Comment by gweeyc** [comment]
Noted and thanks.
