### ISSUE TITLE
Team Dashboard still reporting work not done when done?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#38]
Hi Profs, for our Team 5, we had created all the relevant docs branches and done our updates in them and merged them to the Team 5 Repo successfully. However the Dashboard still shows:
![image](https://user-images.githubusercontent.com/43993134/155946048-cebe41aa-49e4-4b48-a01a-222206e5f5fa.png)

For the jar file reference, we have not created a jar file as we have not coded extension into the addressbook, so we leave the original addressbook jar file instructions intact.

For the rest of the red tags, we already done the updates but still they are undetected by Dashboard? Kindly check and advise us how to resolve the issues. Thank you!

**Comment by damithc** [comment]
@gweeyc It was a problem with stale data. I've fixed it now.

Things to fix on your team repo side:

* https://github.com/AY2122S2-TIC4002-F18-5/tp2/blob/master/README.md originally had a CI banner. The script is checking if it has been updated to point to your repo. Seems like you removed it altogether?
* UG: Either remove the reference to `addressbook.jar` file and add something like `coming soon` for the time being or change it to the name that you plan to give your jar file.

**Comment by gweeyc** [comment]
Noted and thanks!
