### ISSUE TITLE
Github Actions sequences?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#39]
HI Profs, I find that
- For a push to local repo, JavaCI checks will run at the local repo Actions section. 
- When a PR is created from local repo to Team remote repo, another same redundant JavaCI checks will fully run again at the remote Actions section.

Can we turn off JavaCI checks at the local repo? Thank you.

**Comment by damithc** [comment]
yes @gweeyc , there is no need to run CI on your fork. It's enough to run them on the team repo only.

**Comment by gweeyc** [comment]
Noted and thanks.
