### ISSUE TITLE
Can merge branch if tests check failed

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#41]
Can our team proceed to merge the new "log" command addition even if there are some tests failed as we did not do much for tests now for v1.2?
![image](https://user-images.githubusercontent.com/43993134/157023170-e618bf2c-13d1-4b28-bc8d-73851f39bfad.png)

Some report detail shown: 
![image](https://user-images.githubusercontent.com/43993134/157023326-8eafc03a-7aca-45d0-b950-8e1aa18ae6d3.png)

Or how can we turn of the tests check for now if possible?

**Comment by damithc** [comment]
@gweeyc while we recommend keeping CI passing on the master branch all the time, we don't stop you from merging branches that fail CI.

**Comment by gweeyc** [comment]
Noted and thank you.
