### ISSUE TITLE
Need advice for the remaining test cases failed

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#42]
Hi Profs, I can make no more progress as the test cases can be confusing deep in, I need some troubleshooting help in the remaining test cases failure:
![image](https://user-images.githubusercontent.com/43993134/157625801-fe0136cb-15fd-4f8e-8108-eef456a358ca.png)

The error report is hard to understand: file:///C:/Users/ycgwe/Documents/tp2/build/reports/tests/test/index.html ?

**Comment by damithc** [comment]
@gweeyc Are you able to pass these tests locally? i.e., Run each test using Intellij

**Comment by gweeyc** [comment]
Yes, I did the test locally first, and am confused where the error, most probably in configuration settings that is causing the error. Thank you.

**Comment by damithc** [comment]
@gweeyc to confirm,
1. is this a test you added or it existed before?
1. the test case is failing locally? 
2. when you run the one of the failing tests, are you able to see expected vs actual output, in Intellij?
3. can you create a PR for the code and post the link here?

**Comment by gweeyc** [comment]
Hi Prof Damith,
I recently go into the test cases again and run the test, still got a strange error msg I do not understand. I created the PR as you requested as shown here https://github.com/AY2122S2-TIC4002-F18-5/tp2/pull/74

The current first test fail error msg is as shown below:
![image](https://user-images.githubusercontent.com/43993134/158834994-22256276-97a5-4177-b386-e8b617c3c1be.png)

I have not seen this error msg before, confusing for me here, bit deep also. Thank you for your kind help.

**Comment by damithc** [comment]
@gweeyc Based on the error message, the problem is that the class claims to implement a certain interface but it does not implement all the methods specified in the interface. In that case, the class is 'incomplete' and needs to be declared as an abstract class. Alternatively, you can add the missing methods.

**Comment by gweeyc** [comment]
HI Prof,
I've fixed the above issue. Now when I run the test folder again I see this usual report I have first seen before:
![image](https://user-images.githubusercontent.com/43993134/158999229-486b156f-57ee-41fd-bd2e-c1b3ac8a949e.png)

I believe this is due to the log command I had added, but I am not able to fix any of them as I do not know what is really causing them as I had followed the Add a Command steps for the test cases all the way? Maybe my team other CLI commands additions have complicated the issues.

Thank you for your advice and help!

**Comment by damithc** [comment]
@gweeyc this comment might be relevant https://github.com/nus-cs2103-AY2122S2/forum/issues/199#issuecomment-1060211742

Unless you override the `equals` method of a class, comparing two different objects to each other will always return false even if the two objects have similar data inside them.
https://www.infoworld.com/article/3305792/comparing-java-objects-with-equals-and-hashcode.html

**Comment by gweeyc** [comment]
Thanks and noted.
