### ISSUE TITLE
Executing the jar file also creates preferences.json and config.json?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#43]
I tested out the jar version of the program and when it runs, it also creates 2 files locally, preferences.json and config.json ? Is this the default must have feature? Thank you.

**Comment by damithc** [comment]
@gweeyc yes, that's an existing feature of AB3. But you are allowed to change it if you want.

**Comment by gweeyc** [comment]
Noted and thanks!
