### ISSUE TITLE
Tests cases failed

### ISSUE THREAD

**Issue by e0373972** [nus-tic4002-AY2122s2/forum#44]
Hi Prof, I can create a group, assign a person to a group, and add remarks, the program can run without error, but when run check and test, it comes out 2 errors.

![Screenshot 2022-03-15 at 1 34 11 AM](https://user-images.githubusercontent.com/54064995/158234115-2d46fa95-b615-462d-b3e5-df8f95c6235d.jpg)

[Click here to see the code: https://github.com/e0373972/tp2/tree/AssignCommand
](https://github.com/e0373972/tp2/tree/AssignCommand)

Thanks for your help.

**Comment by damithc** [comment]
@e0373972 can you locate one of the failing tests and run it individually, as shown below?
![image](https://user-images.githubusercontent.com/1673303/158240871-b3c6d632-d4d6-43fc-828a-40a12b5b5be1.png)

What's the output you see?

**Comment by e0373972** [comment]
![Screenshot 2022-03-15 at 8 35 15 AM](https://user-images.githubusercontent.com/54064995/158283292-5d9d3d1a-94fe-4d18-b675-9882d927aac2.jpg)

**Comment by e0373972** [comment]
Update the test data, the problem is solved.

**Comment by e0373972** [comment]
Thanks Prof.
