### ISSUE TITLE
What is tagging the repo referring to?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#45]
![image](https://user-images.githubusercontent.com/43993134/159148483-689f052a-0a4c-433d-b3a3-3175e14c70e8.png)

Like to know what the blue highlighted statement refers to? I am unsure about the procedure. Is this different from the jar Release method of creating the tag for the release? Thank you.

**Comment by damithc** [comment]
It means create a git tag, but I think GitHub does that automatically now (if you you specify the version number when creating a release)

**Comment by gweeyc** [comment]
Thanks!
