### ISSUE TITLE
AB3 Logging - Log Level always INFO

### ISSUE THREAD

**Issue by TanChiaChun** [nus-tic4002-AY2122s2/forum#46]
Following instructions from [AB3 DG Logging Guide](https://ay2122s2-tic4002-f18-4.github.io/tp2/Logging.html), despite changing log level via `config.json` to `FINE`, it still remains at `INFO`.

Tested with `WARNING` and it defaults to `INFO` as well.

Below is a reference screenshot.
![Screenshot 2022-03-20 170854](https://user-images.githubusercontent.com/54241577/159155954-054c267a-219d-4458-8064-4ea30fa86580.png)

**Comment by damithc** [comment]
Thanks for reporting this @TanChiaChun I'll get the AB3 developers to take a look.

**Comment by damithc** [comment]
Indeed it seems to be a bug that no one else notices all this time. Good job spotting it @TanChiaChun 👍 
It is unlikely we'll be able to fix it this semester though.

**Comment by TanChiaChun** [comment]
No worries prof, got it
