### ISSUE TITLE
How to achieve the tutorial task in TP progress dashboard

### ISSUE THREAD

**Issue by yinyin377** [nus-tic4002-AY2122s2/forum#47]
Hi, I've merged my PR for tutorial-adding-command branch but it seems like it was not pick up in my progress dashboard.
not sure if any one encountered the same issue, any advise?

My pull request can be found [here](https://github.com/AY2122S2-TIC4002-F18-3/tp2/pull/43)

**Merged status**

<img width="871" alt="Screenshot 2022-03-21 at 2 12 56 PM" src="https://user-images.githubusercontent.com/88772711/159212819-c3c8da80-b2ca-4b5d-a5aa-c9e89bb9b2e9.png">

**tP progress dashboard**

<img width="892" alt="Screenshot 2022-03-21 at 2 14 46 PM" src="https://user-images.githubusercontent.com/88772711/159212916-e547cbfd-bf2a-4a13-81a5-c4ab6a9fedc9.png">

**Comment by damithc** [comment]
@yinyin377 The dashboard stops checking for an item about a week after the deadline for that item is over. It's  OK to have a few red items (it will not affect marks), as long as most items are green.

**Comment by yinyin377** [comment]
noted, prof thanks.
