### ISSUE TITLE
Practical Exam Start Time

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#48]
Hi Profs, the PE start time is listed as April 16th, 6-9pm, however in the admin tP -> Practical Exam guide, it says this:
![image](https://user-images.githubusercontent.com/43993134/160267066-8edb1583-d954-4744-b942-ba90f91d6f75.png)

So the query is how long does this PE lasts, 2 or 3 hours? Does it start from 6 or 7pm ? Thank you!

**Comment by damithc** [comment]
Good catch @gweeyc . I've updated it as `6pm`.

**Comment by gweeyc** [comment]
Thanks
