### ISSUE TITLE
PPP portfolio page how to create?

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#49]
I notice the portfolio hyperlink in our AboutUs.md already points to our PPP githubUserName.md file? But the one we are to create is a html file in a newly created public repo? I am a bit confused as to the PPP site instruction. Thank you!

**Comment by damithc** [comment]
@gweeyc Note how the UserGuide.html page updates automatically when you updates the UserGuide.md file.
Similarly, you need to update the PPP githubUserName.md that you created earlier, and the corresponding html file will update automatically. There is no need to create a new file.

**Comment by gweeyc** [comment]
Ok, got it and thanks!
