### ISSUE TITLE
Cannot submit deliverables

### ISSUE THREAD

**Issue by gweeyc** [nus-tic4002-AY2122s2/forum#50]
I cannot attempt to submit as the File section shows:
![image](https://user-images.githubusercontent.com/43993134/162142543-6193e176-3874-4db9-8274-0614d6a1bf72.png)

![image](https://user-images.githubusercontent.com/43993134/162142119-bdb7dfa5-ee6d-4a8a-af93-af2313af6341.png)

**Comment by damithc** [comment]
Thanks for the reminder @gweeyc I've opened them.

**Comment by gweeyc** [comment]
Thanks!
