### ISSUE TITLE
Jar File not working

### ISSUE THREAD

**Issue by lowyanshuang** [nus-tic4002-AY2122s2/forum#8]
I have generated the jar file base on the instructure here: https://se-education.org/guides/tutorials/gradle.html#creating-a-jar-file using the gradlew shadowJar command but the jar file doesn't run when I click on it. Am I missing something?

**Comment by damithc** [comment]
@lowyanshuang try the below:

1. Open a terminal and navigate to the location where you have the jar file.
1. Check if you are using Java 11 by running the `java -version` command.
1. Launch the JAR using the `java -jar filename.jar` command.

Post the output you see after doing the above.

BTW, also try `./gradlew clean shadowJar` command i.e., include `clean` as well, to force a full rebuild.

**Comment by lowyanshuang** [comment]
Yes I am using Java 11. 
I get this after launching the JAR file "Error: JavaFX runtime components are missing, and are required to run this application"

**Comment by damithc** [comment]
@lowyanshuang which OS are you using?

**Comment by lowyanshuang** [comment]
Windows

**Comment by damithc** [comment]
> * Check if you are using Java 11 by running the `java -version` command.
> * Launch the JAR using the `java -jar filename.jar` command.

@lowyanshuang post a screenshot showing the output of both of these commands.

Also, post the content of your build.gradle file.

**Comment by lowyanshuang** [comment]
1. java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

2. Error: JavaFX runtime components are missing, and are required to run this application

build.gradle

> plugins {
>     id 'java'
>     id 'application'
>     id 'checkstyle'
>     id 'com.github.johnrengelman.shadow' version '5.1.0'
> }
> 
> repositories {
>     mavenCentral()
> }
> 
> dependencies {
>     implementation 'org.jetbrains:annotations:20.1.0'
>     testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
>     testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'
> 
>     String javaFxVersion = '17'
> 
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
>     implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
> }
> 
> test {
>     useJUnitPlatform()
> 
>     testLogging {
>         events "passed", "skipped", "failed"
> 
>         showExceptions true
>         exceptionFormat "full"
>         showCauses true
>         showStackTraces true
>         showStandardStreams = false
>     }
> }
> 
> application {
>     mainClassName = "seedu.duke.Duke"
> }
> 
> shadowJar {
>     archiveBaseName = "duke"
>     archiveClassifier = null
> }
> 
> checkstyle {
>     toolVersion = '8.23'
> }
> 
> run{
>     standardInput = System.in
> 	enableAssertions = true
> }
> 
> jar {
>     manifest {
>         attributes "Main-Class": "com.gradle.tutorial.FizzBuzzProcessor"
>     }
> 
>     from {
>         configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
>     }
> }

**Comment by damithc** [comment]
Did you try `./gradlew clean shadowJar` ? Also check the time stamp of the JAR file to confirm you are not trying to run an old JAR file.

**Comment by lowyanshuang** [comment]
Yes I did try that and have regenerate the jar file yesterday. The date is correct

**Comment by damithc** [comment]
@lowyanshuang push the latest code to a branch and post the link to the branch here. I'll get someone to take a look.

**Comment by lowyanshuang** [comment]
https://github.com/lowyanshuang/ip/tree/A-CI

**Comment by l-shihao** [comment]
Maybe you could try including below to your `build.gradle`: 
```
plugins {
  id 'application'
  id 'org.openjfx.javafxplugin' version '0.0.11'
}

javafx {
    modules = [ 'javafx.controls', 'javafx.fxml']
}
```
according to this [post](https://github.com/nus-tic4002-AY2122s2/forum/issues/1)

**Comment by vimuthm** [comment]
Hi @lowyanshuang , 

Try changing the `mainClassName` property in `build.gradle` to the `Launcher` class like this:

![image](https://user-images.githubusercontent.com/62249192/152671383-e62cf7ab-bf30-4305-9947-5117705aa114.png)

After which you will get a different error, which seems to be due to the missing `/images` folder in `resources` which is accessed by [these](https://github.com/lowyanshuang/ip/blob/96b2e406ab8ad24064da6b53b671e5d2ab571538/src/main/java/seedu/duke/Duke.java#L30) lines in `Duke.java`

**Comment by lowyanshuang** [comment]
Thank you guys for your reply.
I have tried a few of your method and @VimuthM work out nicely. Thank you!
